### ISSUE TITLE
how to disable jupyter lab

### ISSUE THREAD

**Issue by liganega** [jamesdbrock/ihaskell-notebook#7]
I would like to know how to disable jupyter lab at launching the container.
Setting the option `--env JUPYTER_ENABLE_LAB=no` doesn't help.

I know one can still launch classic notebooks, but I just like the classic ones.
My problem with the jupyter lab is the keybinding and look.

**Comment by jamesdbrock** [comment]
If you delete the entire `--env JUPYTER_ENABLE_LAB=yes` argument from the commandline, then you'll get the classic Jupyter notebook.
